# Generated by Django 5.2.2 on 2025-06-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('x', models.FloatField(help_text='X position for star display')),
                ('y', models.FloatField(help_text='Y position for star display')),
                ('color', models.CharField(default='#FFD700', max_length=7)),
            ],
        ),
    ]
