# Generated by Django 5.2.2 on 2025-06-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryentry',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memoryentry',
            name='x',
            field=models.FloatField(default=0, help_text='X position for star display'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryentry',
            name='y',
            field=models.FloatField(default=0, help_text='Y position for star display'),
            preserve_default=False,
        ),
    ]
