# Generated by Django 5.2.3 on 2025-06-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryentry',
            name='color',
            field=models.CharField(default='#ffffff', help_text='Hex color of the star', max_length=7),
        ),
    ]
