# Generated by Django 5.2.3 on 2025-06-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_memoryentry_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memory_images/'),
        ),
    ]
