# Generated by Django 5.2.3 on 2025-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_memoryentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryentry',
            name='profile_picture',
            field=models.CharField(default='avatar1.png', max_length=255),
        ),
    ]
