# Generated by Django 5.2.3 on 2025-06-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_memoryentry_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memory_images/')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journal.memoryentry')),
            ],
        ),
    ]
