# Generated by Django 5.2.3 on 2025-06-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_memoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryentry',
            name='image',
        ),
    ]
